# Site settings
title: WangYang's Blog
SEOTitle: 王阳的博客 | WangYang's Blog
header-img: img/post-bg-desk.jpg
email: 1146049426@qq.com
description: "This is WangYang's blog."
keyword: "WangYang's Blog, 王阳的博客, WangYang, HTML, CSS, Vue.js, js"
url: "http://wangyang1996.github.io"          
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/wangyang1996/wangyang1996.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Action speak louder than words."
sidebar-avatar: /img/avatar_m.jpg   # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:  不想当条咸鱼了   
zhihu_username:   wangyang1996  
github_username:    wangyang1996
#facebook_username:   
#jianshu_username:    
#twitter_username:    




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 22c61b07b0a22ab883b9  #生成的clientID
  clientSecret: 1ffd7d6f9dfd939b07aa34755e5d9d78a817be8b    #生成的clientSecret
  repo: wangyang1996.github.io    #仓库名称
  owner: wangyang1996    #github用户名
  admin: wangyang1996
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: d5d0e013f6ef7c216b05de5b3f187baf

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0             # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Baidu",
        href: "https://www.baidu.com/"
    },{
        title: "Tencent-cloud",
        href: "https://cloud.tencent.com/"
    },{
        title: "Github",
        href: "https://github.com/"
    },{
        title: "Weibo",
        href: "https://weibo.com/"
    }
]
